-- AlterTable
ALTER TABLE "users" ADD COLUMN     "attendanceProgram" TEXT,
ADD COLUMN     "birthday" TIMESTAMP(3),
ADD COLUMN     "childrenCount" INTEGER,
ADD COLUMN     "company" TEXT,
ADD COLUMN     "companyLocation" TEXT,
ADD COLUMN     "currentAddress" TEXT,
ADD COLUMN     "drivingLicenseAttachment" TEXT,
ADD COLUMN     "drivingLicenseExpiryDate" TIMESTAMP(3),
ADD COLUMN     "drivingLicenseNumber" TEXT,
ADD COLUMN     "emailAddresses" TEXT,
ADD COLUMN     "employeeType" TEXT,
ADD COLUMN     "exitDate" TIMESTAMP(3),
ADD COLUMN     "gender" TEXT,
ADD COLUMN     "insuranceAttachment" TEXT,
ADD COLUMN     "insuranceExpiryDate" TIMESTAMP(3),
ADD COLUMN     "insuranceNumber" TEXT,
ADD COLUMN     "isLineManager" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "joiningDate" TIMESTAMP(3),
ADD COLUMN     "labourIdAttachment" TEXT,
ADD COLUMN     "labourIdExpiryDate" TIMESTAMP(3),
ADD COLUMN     "labourIdNumber" TEXT,
ADD COLUMN     "managerId" TEXT,
ADD COLUMN     "maritalStatus" TEXT,
ADD COLUMN     "nationalIdAttachment" TEXT,
ADD COLUMN     "nationalIdExpiryDate" TIMESTAMP(3),
ADD COLUMN     "nationalIdNumber" TEXT,
ADD COLUMN     "nationality" TEXT,
ADD COLUMN     "passportAttachment" TEXT,
ADD COLUMN     "passportExpiryDate" TIMESTAMP(3),
ADD COLUMN     "passportIssueDate" TIMESTAMP(3),
ADD COLUMN     "passportNumber" TEXT,
ADD COLUMN     "phoneNumbers" TEXT,
ADD COLUMN     "remarks" TEXT,
ADD COLUMN     "residencyAttachment" TEXT,
ADD COLUMN     "residencyExpiryDate" TIMESTAMP(3),
ADD COLUMN     "residencyNumber" TEXT,
ADD COLUMN     "status" TEXT,
ADD COLUMN     "userAccount" BOOLEAN NOT NULL DEFAULT false;

-- AddForeignKey
ALTER TABLE "users" ADD CONSTRAINT "users_managerId_fkey" FOREIGN KEY ("managerId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
